// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer_proto.proto

package com.mbrdi.protobufs;

public final class CustomerProtoOuterClass {
  private CustomerProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mbrdi_protobufs_CustomerTransferProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mbrdi_protobufs_CustomerTransferProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mbrdi_protobufs_CustomerProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mbrdi_protobufs_CustomerProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024customer_proto.proto\022\023com.mbrdi.protob" +
      "ufs\"\234\001\n\025CustomerTransferProto\022\026\n\tis_upda" +
      "te\030\001 \001(\010H\000\210\001\001\022\027\n\nis_xmlfile\030\002 \001(\010H\001\210\001\001\0225" +
      "\n\tcustomers\030\003 \003(\0132\".com.mbrdi.protobufs." +
      "CustomerProtoB\014\n\n_is_updateB\r\n\013_is_xmlfi" +
      "le\"\227\001\n\rCustomerProto\022\017\n\002id\030\001 \001(\005H\000\210\001\001\022\021\n" +
      "\004name\030\002 \001(\tH\001\210\001\001\022\020\n\003dob\030\003 \001(\tH\002\210\001\001\022\023\n\006sa" +
      "lary\030\004 \001(\tH\003\210\001\001\022\020\n\003age\030\005 \001(\005H\004\210\001\001B\005\n\003_id" +
      "B\007\n\005_nameB\006\n\004_dobB\t\n\007_salaryB\006\n\004_ageB0\n\023" +
      "com.mbrdi.protobufsB\027CustomerProtoOuterC" +
      "lassP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mbrdi_protobufs_CustomerTransferProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mbrdi_protobufs_CustomerTransferProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mbrdi_protobufs_CustomerTransferProto_descriptor,
        new java.lang.String[] { "IsUpdate", "IsXmlfile", "Customers", "IsUpdate", "IsXmlfile", });
    internal_static_com_mbrdi_protobufs_CustomerProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mbrdi_protobufs_CustomerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mbrdi_protobufs_CustomerProto_descriptor,
        new java.lang.String[] { "Id", "Name", "Dob", "Salary", "Age", "Id", "Name", "Dob", "Salary", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
