// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer_proto.proto

package com.mbrdi.protobufs;

public interface CustomerTransferProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mbrdi.protobufs.CustomerTransferProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool is_update = 1;</code>
   * @return Whether the isUpdate field is set.
   */
  boolean hasIsUpdate();
  /**
   * <code>optional bool is_update = 1;</code>
   * @return The isUpdate.
   */
  boolean getIsUpdate();

  /**
   * <code>optional bool is_xmlfile = 2;</code>
   * @return Whether the isXmlfile field is set.
   */
  boolean hasIsXmlfile();
  /**
   * <code>optional bool is_xmlfile = 2;</code>
   * @return The isXmlfile.
   */
  boolean getIsXmlfile();

  /**
   * <code>repeated .com.mbrdi.protobufs.CustomerProto customers = 3;</code>
   */
  java.util.List<com.mbrdi.protobufs.CustomerProto> 
      getCustomersList();
  /**
   * <code>repeated .com.mbrdi.protobufs.CustomerProto customers = 3;</code>
   */
  com.mbrdi.protobufs.CustomerProto getCustomers(int index);
  /**
   * <code>repeated .com.mbrdi.protobufs.CustomerProto customers = 3;</code>
   */
  int getCustomersCount();
  /**
   * <code>repeated .com.mbrdi.protobufs.CustomerProto customers = 3;</code>
   */
  java.util.List<? extends com.mbrdi.protobufs.CustomerProtoOrBuilder> 
      getCustomersOrBuilderList();
  /**
   * <code>repeated .com.mbrdi.protobufs.CustomerProto customers = 3;</code>
   */
  com.mbrdi.protobufs.CustomerProtoOrBuilder getCustomersOrBuilder(
      int index);
}
